EEData.Autocomplete ||= {}

EEData.Autocomplete['meds'] = [
  "Abilify (aripiprazole)"
  "Adderall (amphetamine)"
  "Adderall XR (amphetamine- extended release)"
  "Anafranil (clomipramine)"
  "Asendin (amoxapine)"
  "Ativan (Lorazepam)"
  "Aventyl (nortriptyline)"
  "BuSpar (buspirone)"
  "Celexa (citalopram)"
  "Clozaril (clozapine)"
  "Concerta (methylphenidate – long acting)"
  "Cymbalta (duloxetine)"
  "Daytrana (methylphenidate patch)"
  "Depakote (divalproex sodium)"
  "Desoxyn (methamphetamine)"
  "Desyrel (Trazodone)"
  "Dexedrine (dextroamphetamine)"
  "Dextrostat (dextroamphetamine)"
  "Effexor (venlafaxine)"
  "Elavil (amitriptyline)"
  "Emsam (selegiline)"
  "Eskalith (lithium carbonate)"
  "Fanapt (iloperidone)"
  "Fluphenazine"
  "Focalin (dexmethylphenidate)"
  "Focalin XR (dexmethylphenidate- extended release)"
  "Geodon (ziprasidone)"
  "Haldol (haloperidol)"
  "Intuniv (guanfacine)"
  "Invega (paliperidone)"
  "Klonopin (clonazepam)"
  "Lamictal (lamotrigine)"
  "Lexapro (escitalopram)"
  "Librium (chlordiazepoxide)"
  "Lithobid (lithium carbonate)"
  "Lithium Citrate"
  "Loxitane (loxapine)"
  "Ludiomil (maprotiline)"
  "Luvox (fluvoxamine)"
  "Marplan (isocarboxazid)"
  "Metadate CD (methylphenidate- extended release)"
  "Metadate ER (methylphenidate- extended release)"
  "Methylin (methylphenidate)"
  "Moban (molindone)"
  "Nardil (phenelzine)"
  "Navane (thiothixene)"
  "Neurontin (gabapentin)"
  "Norpramin (desipramine)"
  "Orap (pimozide)"
  "Other"
  "Pamelor (nortriptyline)"
  "Parnate (tranylcypromine)"
  "Paxil (paroxetine)"
  "Perphenazine"
  "Pexeva (paroxetine-mesylate)"
  "Pristiq (desvenlafaxine)"
  "Prozac (fluoxetine)"
  "Remeron (mirtazapine)"
  "Risperdal (risperidone)"
  "Ritalin (methylphenidate)"
  "Ritalin LA (methylphenidate- long acting)"
  "Ritalin SR (methylphenidate- extended release)"
  "Sarafem (fluoxetine)"
  "Serax (Oxazepam)"
  "Seroquel (quetiapine)"
  "Sinequan (doxepin)"
  "Stelazine (olanzapine)"
  "Strattera (atomoxetine)"
  "Surmontil (trimipramine)"
  "Symbyax (Prozac &amp; Zyprexa- fluoxetine &amp; olanzapine)"
  "Tegretol (carbamazepine)"
  "Thioridazine"
  "Thorazine (chlorpromazine)"
  "Tofranil (imipramine)"
  "Tofranil-PM (imipramine pamoate)"
  "Topamax (topiramate)"
  "Tranxene (clorazepate)"
  "Trileptal (oxcarbazepine)"
  "Valium (diazepam)"
  "Vivactil (protriptyline)"
  "Vyvanse (lisdexamfetamine dimesylate)"
  "Wellbutrin (bupropion)"
  "Xanax (alprazolam)"
  "Zoloft (sertraline)"
  "Zyprexa (olanzapine)"
]
